### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by dialexo** [graasp/graasp-websockets#1]
## Tasks

General roadmap of the graasp-websockets project. Tasks that require additional comments and tracking will get their own issues.

Milestones:

- [x] Simple broadcast abstraction over barebone websockets
- [x] Integrate `fastify-websockets` and expose a fastify plugin (packed with `fastify-plugin`) #2 
- [x] Channels abstraction with pub / sub mechanism
- [x] Design `Message` type
- [x] Validation of client messages
- [x] Hearbeat to keep list of connected clients up-to-date and avoid memory leaks (see https://github.com/websockets/ws#how-to-detect-and-close-broken-connections)
- [x] Garbage collection of unused channels ?
- [x] Integrate into graasp tasks using postHookHandlers
- [x] Front-end integration
- [x] Redis multi-instance layer

Fluff:

- [x] Use semicolons, linter
- [x] Write docs (together with code)
- [x] Setup testing framework (Jest?)
- [x] Setup CI with Github Actions (test, lint, coverage). See https://github.com/nektos/act for local setup?
- [x] Better README with examples and all the good stuff

## Notes

Using `npm ci`  instead of `npm install` in `.github/workflows/main.yml` results in SSH key errors in CI. Use `npm install` instead.

## Misc

- Should we remove `Message` types and subtypes and keep only types derived from `message-schema.ts`? Pro: no duplication, con: rely on AJV + JTD. Also, can TS still discriminate union types with JTD's `discriminator`?

**Comment by dialexo** [comment]
Use redis, fastify-redis for in-memory storage

**Comment by dialexo** [comment]
Use semicolons
